import { precacheAndRoute } from 'workbox-precaching';

// Precache the assets listed in the __WB_MANIFEST array (this will be generated by Workbox during the build process)
precacheAndRoute(self.__WB_MANIFEST);

// Listen for fetch events (for network requests made by the app)
self.addEventListener('fetch', (event) => {
    event.respondWith(
        caches.match(event.request).then((cachedResponse) => {
            // If a cached response is found, return it, otherwise fetch the request from the network
            return cachedResponse || fetch(event.request);
        })
    );
});
